routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\TaskController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::name('tasks.index')->group(function(){
    Route::get('/', [TaskController::class,'index']);
    Route::get('tasks',[TaskController::class,'index']);
});

Route::group(['prefix' => 'tasks', 'middleware' => ['auth.tasks'], 'as' => 'tasks.'], function () {
    Route::post('/', [TaskController::class, 'store'])->name('store');
    Route::get('/{task}/edit', [TaskController::class, 'edit'])->name('edit');
    Route::put('/{task}', [TaskController::class, 'update'])->name('update');
    Route::delete('/{task}', [TaskController::class, 'destroy'])->name('destroy');
    Route::get('/create', [TaskController::class, 'create'])->name('create');
});


Auth::routes();
Route::post('logout', [LoginController::class, 'logout'])->name('logout');
Route::get('home', [HomeController::class, 'index'])->name('home');
Route::get('tasks/search', [TaskController::class, 'search'])->name('tasks.search');

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;
    protected $table='tasks';
    protected $fillable=['name','context'];
    public function scopeSearch($query, $keyword)
    {
        return $query->where('name', 'LIKE', "%$keyword%")
            ->orWhere('context', 'LIKE', "%$keyword%");
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTaskRequest;
use App\Models\Task;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class TaskController extends Controller
{
    protected $task;

    /**
     * @param $task
     */
    public function __construct(Task $task)
    {
        $this->task = $task;
    }

    public function index()
    {
        $tasks = Task::paginate(10);
        $countTask = Task::count();

        return view('tasks.index', compact('tasks', 'countTask'));
    }

    public function store(CreateTaskRequest $request)
    {
        $this->task->create($request->all());

        return redirect()->route('tasks.index')->with('success', 'Thêm task thành công ');
    }

    public function create()
    {
        return view('tasks.create');
    }

    public function edit($id)
    {
        $task = Task::find($id);

        if (!$task) {
            return redirect()->route('tasks.index')->with('error', 'Task not found');
        }

        return view('tasks.edit', compact('task'));
    }

    public function update(Request $request, $id)
    {
        $task = Task::find($id);

        if (!$task) {
            return redirect()->route('tasks.index')->with('error', 'Task not found');
        }

        // Perform validation and update logic here
        // ...

        $task->update([
            'name' => $request->input('name'),
            'context' => $request->input('context'),
        ]);

        // Redirect to the index view after update
        return redirect()->route('tasks.index')->with('success', 'Update task thành công');
    }

    public function destroy($id)
    {
        $task = Task::find($id);

        if (!$task) {
            return redirect()->route('tasks.index')->with('error', 'Task not found');
        }

        $task->delete();

        return redirect()->route('tasks.index')->with('success', 'Xóa task thành công ');
    }

    public function search(Request $request)
    {
        $keyword = $request->input('keyword');

        // Sử dụng scopeSearch để tìm kiếm
        $tasks = Task::search($keyword)->paginate(10);

        return view('tasks.index', compact('tasks', 'keyword'));
    }
}

resources/views/home.blade.php
@extends('layout.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Trang chủ ') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('Bạn đã đăng nhập!') }}
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('logout') }}">
                        @csrf
                        <button class="btn btn-primary" type="submit">Đăng Xuất</button>
                    </form>
                </div>
                <div class="card-body">
                    <a href="{{route('tasks.index')}}"  class="btn btn-success"> List Task </a>
                </div>

            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layout/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield('title', 'Laravel App')</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>
<body>
<div class="container mt-4">
    @yield('content')
</div>

<!-- jQuery and Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="{{ asset('js/app.js') }}" defer></script>
</body>
</html>

resources/views/tasks/create.blade.php
@extends('layout.app')

@section('content')
    <div class="container">
        <div class="row justify-content-end">
            <div class="col-md-4">
                <form method="POST" action="{{ route('logout') }}">
                    @csrf
                    <button type="submit" class="btn btn-danger">Đăng Xuất</button>
                </form>
            </div>
        </div>

        <div class="row justify-content-center mt-4">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h2>Tạo task</h2>
                    </div>

                    <div class="card-body">
                        <form action="{{ route('tasks.store') }}" method="POST">
                            @csrf

                            <div class="mb-3">
                                <label for="name" class="form-label">Tên</label>
                                <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" placeholder="Enter task name">
                                @error('name')
                                <span class="invalid-feedback" role="alert">{{ $message }}</span>
                                @enderror
                            </div>

                            <div class="mb-3">
                                <label for="context" class="form-label">Nội dung</label>
                                <input type="text" class="form-control" name="context" placeholder="Enter task context">
                            </div>

                            <button type="submit" class="btn btn-success">Tạo</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/tasks/edit.blade.php
@extends('layout.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Sửa </div>
                    <div class="card-body">
                        <form action="{{ route('tasks.update', ['task' => $task->id]) }}" method="POST">
                            @csrf
                            @method('PUT')

                            <div class="form-group">
                                <label for="name">Tên:</label>
                                <input type="text" name="name" class="form-control" value="{{ $task->name }}">
                            </div>

                            <div class="form-group">
                                <label for="context">Nội dung:</label>
                                <textarea name="context" class="form-control">{{ $task->context }}</textarea>
                            </div>

                            <button type="submit" class="btn btn-primary">Cập nhật Task</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/tasks/index.blade.php
 @extends(('layout.app'))

@section('content')


    <div class="container">
        <div class="logout" >
            @if(auth()->check()) {{-- Check if the user is authenticated --}}
            <form method="POST" action="{{ route('logout') }}">
                @csrf
                <button class= "btn btn-danger" type="submit">Đăng Xuất</button>
            </form>
            @else
                <a class= "btn btn-primary" href="{{ route('login') }}">Đăng Nhập</a>
            @endif
        </div>
        <div class="create" >
            <a class= "btn btn-primary" href="{{ route('tasks.create') }}">Tạo task</a>
        </div>

        <form action="{{ route('tasks.search') }}" method="GET">
            <div class="input-group mb-3">
                <input type="text" class="form-control" placeholder="Tìm kiếm..." name="keyword">
                <div class="input-group-append">
                    <button class="btn btn-primary " type="submit">Tìm kiếm</button>
                </div>
            </div>
        </form>

        <!-- Hiển thị kết quả tìm kiếm (nếu có) -->
        @if(isset($keyword))
            <div class="alert alert-info" role="alert">
                Kết quả tìm kiếm cho "{{ $keyword }}":
            </div>
        @endif
        <div>
            <p> Tổng số task là : {{ $countTask }}</p>
        </div>
        <div class="row justify-content-center">
            <table class="table table-striped">
                @if (session('success'))
                     <div class="alert alert-success">
                         {{session('success')}}
                     </div>
                @endif
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Tên</th>
                    <th>Nội dung</th>
                    <th></th> <!-- Thêm cột Actions -->
                </tr>
                </thead>
                <tbody>
                @foreach($tasks as $task)
                    <tr>
                        <td>{{ $task->id }}</td>
                        <td>{{ $task->name }}</td>
                        <td>{{ $task->context }}</td>
                        <td>
                            <!-- Thêm nút sửa -->
                            <a href="{{ route('tasks.edit', ['task' => $task->id]) }}" class="btn btn-primary">Sửa</a>
                            <div style="margin-top:5px;">
                            <form action="{{ route('tasks.destroy', ['task' => $task->id]) }}" method="POST" style="display:inline;">
                                @csrf
                                @method('DELETE')
                                <button type="button" class="btn btn-danger" onclick="confirmDelete('{{ $task->id }}')">Xóa</button>
                            </form>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <div class="d-flex justify-content-center mt-4">
        {{ $tasks->links('pagination::bootstrap-4') }}
    </div>
@endsection